name: ConnectedIP
version: 1.0.0
author: Matthww
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
description: Shows info about a certain player!
main: Matthww\connectedip\connectedip

commands:
 connectedip:
  description: Show info about a certain player!
  usage: "/connectedip <player>"
  permission: connectedip.use
  aliases: ['cip']
permissions:
  connectedip:
    default: false
    children:
      joinedip.use:
        default: op
        description: "Allows the user to run the connectedip command"
